name: Publish Docker Images

on:
  push:
    tags:
      - '**'

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: rockstorm/radicale
        tags: |
          # build (i.e. 1.2.3+b4)
          type=ref,event=tag,priority=600
          # patch (i.e. 1.2.3)
          type=match,pattern=^\d+\.\d+\.\d+,priority=500
          # minor (i.e. 1.2)
          type=match,pattern=^\d+\.\d+,priority=400

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: 'rockstorm'
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: |
          linux/386
          linux/amd64
          linux/arm/v6
          linux/arm/v7
          linux/arm64/v8
          linux/ppc64le
          linux/s390x
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
